name: Check Course Seats

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:        # Allows manual trigger

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run seat checker
        run: python main.py
