name: check_seats

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-python:
    runs-on: ubuntu-latest  # Free GitHub-hosted runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Pulls your repo into the runner
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Choose your Python version
          
      - name: Install dependencies (if any)
        run: pip install -r requirements.txt  # Only if you have dependencies
        
      - name: Run Python script
        run: python main.py  # Replace with your script name
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          URL: ${{ secrets.URL }}
